export enum ActivityEnum {
  SWIMMING = "SWIMMING",
  BODY_BUILDING = "BODY_BUILDING",
  MARTIAL_ARTS = "MARTIAL_ARTS",
  GYMNASTICS = "GYMNASTICS",
  FOOTBALL = "FOOTBALL",
  TENNIS = "TENNIS",
  RUGBY = "RUGBY",
  HANDBALL = "HANDBALL",
  BASEBALL = "BASEBALL",
  NO_ACTIVITY = "NO_ACTIVITY"
}
